### ISSUE TITLE
Alternative Lock() API

### ISSUE THREAD

**Issue by msiebuhr** [klauspost/shutdown#1]
Have `Lock()` return either the `unlock()` function or `nil` if shutting down. Pending taste, it might lead to a more idiomatic API:

``` go
unlock := Lock()

if unlock == nil {
    // Shutting down
}
defer unlock()
```

Untested implementation idea:

``` go
func Lock() func() {
    srM.RLock()
    s := shutdownRequested
    if !s { wg.Add(1) }
    srM.RUnlock()
    if s { return nil }
    return wg.Done
}
```

**Comment by msiebuhr** [comment]
Implementation: http://play.golang.org/p/KuS3M2v-jz

**Comment by klauspost** [comment]
I think this would be the closest to "sync" package: http://play.golang.org/p/dEz2v5cS9H

However, I considered this, and I didn't really see the advantage. Compare the client code:

``` Go
    u := shutdown.Lock()
    if u == nil {
        fmt.Println("SHUTTING DOWN")
        return
    }
    defer u.Unlock()
```

to the current code

``` Go
    if shutdown.Lock() {
        fmt.Println("SHUTTING DOWN")
        return
    }
    defer shutdown.Unlock()
```

The difference is small, but I thought I might as well go for the shortest possible code.
